INSERT INTO tunes (trackname, artistname, genre, link)

VALUES
  ('Earth Angel', 'The Penguins', 'Doo Wop', ''),
  ('Blue Moon', 'The Marcels', 'Doo Wop', ''),
  ('Put Your Head On My Shoulders', 'Paul Anka', 'Doo Wop', ''),
  ('Teenager In Love', 'Dion DiMucci', 'Doo Wop', ''),
  ('Pretty Woman', 'Roy Orbison', 'Doo Wop', ''),
  ('End Of The Road', 'Boyz 2 Men', 'R&B'),
  ('Confessions', 'Usher', 'R&B'),
  ('Differences', 'Ginuwine', 'R&B'),
  ('Ex-Factor', 'Lauryn Hill', 'R&B'),
  ('One In A Million', 'Aaliyah', 'R&B'),
  ('And I Love Her', 'Brad Mehldau Trio', 'Contemporary Jazz'),
  ('Gefion', 'Jakob Bro', 'Contemporary Jazz'),
  ('America Undefined', 'Pat Metheny', 'Contemporary Jazz'),
  ('Verona', 'Gilad Hekselman', 'Contemporary Jazz'),
  ('When God Created The Coffeebreak', 'Esbjorn Svensson Trio', 'Contemporary Jazz'),
  ('Beat Street', 'Jeff Ballard Trio', 'Contemporary Jazz'),
  ('Skylark', 'Lionel Loueke', 'Contemporary Jazz'),
  ('The Ocean', 'Led Zeppelin', 'Rock'),
  ('Stairway to Heaven', 'Led Zeppelin', 'Rock'),
  ('Rock and Roll', 'Led Zeppelin', 'Rock'),
  ('Echoes', 'Pink Floyd', 'Rock'),
  ('Another Brick in the Wall', 'Pink Floyd', 'Rock'),
  ('Brain Damage', 'Pink Floyd', 'Rock'),
  ('War Pigs', 'Black Sabbath', 'Rock'),
  ('21st Century Schizoid Man', 'King Crimson', 'Rock'),
  ('Loose Change', 'Royal Blood', 'Rock'),
  ('King Kunta', 'Kendrick Lamar', 'Hip Hop', 'https://www.youtube.com/watch?v=hRK7PVJFbS8'),
  ('Humble', 'Kendrick Lamar', 'Hip Hop', 'https://www.youtube.com/watch?v=tvTRZJ-4EyI'),
  ('Poetic Justice', 'Kendrick Lamar', 'Hip Hop', 'https://www.youtube.com/watch?v=yyr2gEouEMM'),
  ('3005', 'Childish Gambino', 'Hip Hop', 'https://www.youtube.com/watch?v=tG35R8F2j8k'),
  ('Gangsta''s Paradise', 'Coolio, Kylian Mash & Rico Bernasconi', 'Hip Hop', 'https://www.youtube.com/watch?v=fPO76Jlnz6c'),
  ('Down For The Count', 'Reflection Eternal', 'Hip Hop', 'https://www.youtube.com/watch?v=AYhX3ew9-wA'),
  ('Power', 'Rapsody', 'Hip Hop', 'https://www.youtube.com/watch?v=c3W3QDSET1I'),
  ('Penitentiary Philosophy', 'Erykah Badu', 'Hip Hop', 'https://www.youtube.com/watch?v=sVQ90z3EYVQ'),
  ('Devil''s Pie', 'D''Angelo', 'Hip Hop', 'https://www.youtube.com/watch?v=8fNtipp5RLs'),
  ('The Light', 'Common', 'Hip Hop', 'https://www.youtube.com/watch?v=OjHX7jf-znA');